DEVICE_PATH := device/xiaomi/spinel

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi

TARGET_SUPPORTS_64_BIT_APPS := true
TARGET_IS_64_BIT := true

TARGET_BOARD_PLATFORM := mt6789
TARGET_BOOTLOADER_BOARD_NAME := mt6789

BOARD_BOOT_HEADER_VERSION := 4
BOARD_VENDOR_BOOT_HEADER_VERSION := 4
BOARD_PAGE_SIZE := 4096

BOARD_USES_VENDOR_BOOT := true

AB_OTA_UPDATER := true

FOX_VIRTUAL_AB_DEVICE := 1

OF_FORCE_PREBUILT_KERNEL := 1

TW_INCLUDE_FASTBOOTD := true
