DEVICE_PATH := device/xiaomi/spinel

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a

TARGET_BOARD_PLATFORM := mt6789
TARGET_BOOTLOADER_BOARD_NAME := mt6789

BOARD_BOOT_HEADER_VERSION := 4
BOARD_VENDOR_BOOT_HEADER_VERSION := 4
BOARD_PAGE_SIZE := 4096

BOARD_USES_VENDOR_BOOT := true

AB_OTA_UPDATER := true

FOX_VIRTUAL_AB_DEVICE := 1

OF_FORCE_PREBUILT_KERNEL := 1

TW_INCLUDE_FASTBOOTD := true
